# Generated by Django 3.1.4 on 2021-02-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='header',
        ),
    ]
