# Generated by Django 3.1.4 on 2021-03-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalPathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='chemical pathology', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RenalFunctionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea', models.CharField(max_length=30)),
                ('Na', models.CharField(max_length=30)),
                ('HCO3', models.CharField(max_length=30)),
                ('Cl', models.CharField(max_length=30)),
                ('creatinine', models.CharField(max_length=30)),
                ('chemicalpathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_report.chemicalpathology')),
            ],
        ),
        migrations.CreateModel(
            name='LiverFunctionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alkaline_Phosphate', models.CharField(max_length=30)),
                ('ALT', models.CharField(max_length=30)),
                ('AST', models.CharField(max_length=30)),
                ('Total_Bilirubin', models.CharField(max_length=30)),
                ('Direct_Bilirubin', models.CharField(max_length=30)),
                ('Total_Protein', models.CharField(max_length=30)),
                ('Albumin', models.CharField(max_length=30)),
                ('Globulin', models.CharField(max_length=30)),
                ('chemicalpathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_report.chemicalpathology')),
            ],
        ),
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fasting', models.CharField(max_length=30)),
                ('Random', models.CharField(max_length=30)),
                ('two_hours_PP', models.CharField(max_length=30)),
                ('chemicalpathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_report.chemicalpathology')),
            ],
        ),
    ]
