# Generated by Django 3.1.4 on 2021-03-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodglucose',
            name='chemicalpathology',
        ),
        migrations.RemoveField(
            model_name='liverfunctiontest',
            name='chemicalpathology',
        ),
        migrations.RemoveField(
            model_name='renalfunctiontest',
            name='chemicalpathology',
        ),
        migrations.DeleteModel(
            name='ChemicalPathology',
        ),
    ]
