# Generated by Django 3.1.4 on 2021-03-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_report', '0002_auto_20210325_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodglucose',
            name='test',
            field=models.CharField(default='Blood Glucose', max_length=30),
        ),
        migrations.AddField(
            model_name='liverfunctiontest',
            name='test',
            field=models.CharField(default='Liver Funtion Test', max_length=30),
        ),
        migrations.AddField(
            model_name='renalfunctiontest',
            name='test',
            field=models.CharField(default='Renal Funtion Test', max_length=30),
        ),
    ]
