# Generated by Django 3.1.7 on 2021-07-21 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_report', '0005_auto_20210326_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglucose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloods', to=settings.AUTH_USER_MODEL),
        ),
    ]
