# Generated by Django 3.1.7 on 2021-07-22 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_report', '0006_auto_20210721_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renalfunctiontest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renals', to=settings.AUTH_USER_MODEL),
        ),
    ]
