# Generated by Django 3.1.4 on 2021-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=90)),
            ],
        ),
    ]
