# Generated by Django 3.1.7 on 2021-04-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_staffs', '0002_nurse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Others',
        ),
    ]
