# Generated by Django 3.1.7 on 2021-04-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_staffs', '0003_auto_20210409_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='others',
            options={'verbose_name_plural': 'Others'},
        ),
    ]
