# Generated by Django 3.1.7 on 2021-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_staffs', '0005_auto_20210409_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
