# Generated by Django 3.1.7 on 2021-07-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(help_text='yy-mm-dd')),
                ('next_of_kin', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('address_of_next_of_kin', models.TextField()),
                ('phone_of_next_of_kin', models.CharField(max_length=20)),
                ('place_of_origin', models.CharField(max_length=30)),
                ('tribe', models.CharField(blank=True, max_length=30, null=True)),
                ('religion', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Patient File',
                'verbose_name_plural': 'Patients File',
            },
        ),
        migrations.CreateModel(
            name='ObservationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='student', max_length=50)),
                ('firstname', models.CharField(max_length=90)),
                ('age', models.CharField(default='20', max_length=10)),
                ('card_no', models.CharField(max_length=15)),
                ('BP', models.CharField(default='student', max_length=20)),
                ('temperature', models.CharField(max_length=10)),
                ('pulse', models.CharField(max_length=15)),
                ('respiration', models.CharField(max_length=15)),
                ('medication', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patientfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsrecords.patientfile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='student', max_length=50)),
                ('name', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('Male', 'male'), ('female', 'female')], max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('occupation', models.CharField(default='student', max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('patientfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsrecords.patientfile')),
            ],
        ),
    ]
